"""Byte-parity tests for the Yggdrasil encrypted session layer.

Vectors generated by a Go program at ``/tmp/gen_vectors/session/main.go``
that re-implements ``ironwood/encrypted/session.go``'s
``sessionInit.encrypt`` and the SessionTypeTraffic packing using the
same primitives upstream uses (``crypto/ed25519`` +
``golang.org/x/crypto/nacl/box``) but takes the otherwise-random
ephemeral box keypair as an argument so the wire bytes are
reproducible.

For SessionInit/Ack: each line carries the seeds + the ephemeral
box keypair the generator used, plus the resulting wire-format
bytes.  The Python side calls ``SessionInit.encode`` with the
``test_ephemeral_box_keypair`` kwarg pinned to the same pair and
asserts byte-for-byte equality with the Go output, then runs
``SessionInit.decode`` against the same bytes and asserts the
fields are recovered.

For SessionTypeTraffic: each line carries the precomputed shared
key + nonce + seqs + next_pub + inner message, plus the wire
bytes the generator produced.  The Python side rebuilds the wire
using ``nacl_box.seal_precomputed`` + ``encode_uvarint`` and
asserts equality with the Go output.

Format of ``tests/yggdrasil_session_vectors.txt``:
  INIT|fromSeed|toSeed|fromBoxPriv|fromBoxPub|current|next|keySeq|seq|typeByte|wire
  TRAFFIC|shared|localKeySeq|remoteKeySeq|nonce|nextPub|msg|wire
Comment lines start with ``#`` and are skipped.
"""
import binascii
import os
import unittest

from aionetiface.testing import AsyncTestCase

from warpgate.overlay.yggdrasil.curve25519 import (
    ed25519_priv_seed_to_curve25519,
    edwards_y_to_montgomery_u,
)
from warpgate.overlay.yggdrasil.encrypted import (
    SESSION_TYPE_INIT,
    SESSION_TYPE_ACK,
    SESSION_TYPE_TRAFFIC,
    SessionInit,
    derive_box_keys_from_ed_seed,
)
from warpgate.overlay.yggdrasil import nacl_box
from warpgate.overlay.yggdrasil.wire import encode_uvarint


VECTOR_PATH = os.path.join(
    os.path.dirname(__file__),
    "yggdrasil_session_vectors.txt",
)


def load_vectors():
    """Return (init_vectors, traffic_vectors)."""
    init_v = []
    traffic_v = []
    with open(VECTOR_PATH, "r") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("|")
            section = parts[0]
            if section == "INIT" and len(parts) == 11:
                init_v.append({
                    "from_seed": binascii.unhexlify(parts[1]),
                    "to_seed": binascii.unhexlify(parts[2]),
                    "from_box_priv": binascii.unhexlify(parts[3]),
                    "from_box_pub": binascii.unhexlify(parts[4]),
                    "current": binascii.unhexlify(parts[5]),
                    "next": binascii.unhexlify(parts[6]),
                    "key_seq": int(parts[7]),
                    "seq": int(parts[8]),
                    "type_byte": int(parts[9]),
                    "wire": binascii.unhexlify(parts[10]),
                })
            elif section == "TRAFFIC" and len(parts) == 8:
                traffic_v.append({
                    "shared": binascii.unhexlify(parts[1]),
                    "local_key_seq": int(parts[2]),
                    "remote_key_seq": int(parts[3]),
                    "nonce": int(parts[4]),
                    "next_pub": binascii.unhexlify(parts[5]),
                    "msg": binascii.unhexlify(parts[6]),
                    "wire": binascii.unhexlify(parts[7]),
                })
    return init_v, traffic_v


def derive_ed_pub_from_seed(seed):
    """Derive the ed25519 public key (32 bytes) from a seed."""
    # The existing helper computes the box AND the ed pub.
    _, _, ed_pub = derive_box_keys_from_ed_seed(seed)
    return ed_pub


class TestSessionInitVectors(AsyncTestCase):
    """Byte-parity encode/decode for SessionInit + SessionAck."""

    async def asyncSetUp(self):
        self.init_vectors, self.traffic_vectors = load_vectors()
        self.assertGreater(len(self.init_vectors), 0,
                           "no INIT vectors loaded")
        self.assertGreater(len(self.traffic_vectors), 0,
                           "no TRAFFIC vectors loaded")

    async def test_init_encode_byte_parity(self):
        """SessionInit.encode with pinned ephemeral keys == Go output."""
        for idx, v in enumerate(self.init_vectors):
            to_ed_pub = derive_ed_pub_from_seed(v["to_seed"])
            init = SessionInit(
                current=v["current"], next_pub=v["next"],
                key_seq=v["key_seq"], seq=v["seq"],
            )
            wire = init.encode(
                v["from_seed"], to_ed_pub,
                type_byte=v["type_byte"],
                test_ephemeral_box_keypair=(v["from_box_priv"],
                                            v["from_box_pub"]),
            )
            self.assertEqual(
                binascii.hexlify(wire).decode(),
                binascii.hexlify(v["wire"]).decode(),
                "INIT vector {0} byte mismatch (type={1})".format(
                    idx, v["type_byte"]),
            )

    async def test_init_decode_recovers_fields(self):
        """SessionInit.decode on Go-produced bytes recovers all fields."""
        for idx, v in enumerate(self.init_vectors):
            # Recipient's box private key = ed25519 seed -> curve25519
            # (matches what EncryptedPacketConn uses for self.box_priv).
            my_box_priv = ed25519_priv_seed_to_curve25519(v["to_seed"])
            from_ed_pub = derive_ed_pub_from_seed(v["from_seed"])
            decoded = SessionInit.decode(
                v["wire"], my_box_priv, from_ed_pub,
            )
            self.assertIsNotNone(
                decoded,
                "INIT vector {0} decode returned None".format(idx),
            )
            self.assertEqual(decoded.current, v["current"],
                             "vector {0} current mismatch".format(idx))
            self.assertEqual(decoded.next, v["next"],
                             "vector {0} next mismatch".format(idx))
            self.assertEqual(decoded.key_seq, v["key_seq"],
                             "vector {0} key_seq mismatch".format(idx))
            self.assertEqual(decoded.seq, v["seq"],
                             "vector {0} seq mismatch".format(idx))

    async def test_init_decode_rejects_tampered_wire(self):
        """Flipping any byte in the wire invalidates the signature/MAC."""
        if not self.init_vectors:
            self.skipTest("no vectors")
        v = self.init_vectors[0]
        my_box_priv = ed25519_priv_seed_to_curve25519(v["to_seed"])
        from_ed_pub = derive_ed_pub_from_seed(v["from_seed"])
        wire = bytearray(v["wire"])
        # Flip a bit in the sealed payload (past the type byte +
        # from_box_pub header).
        wire[40] ^= 0x01
        decoded = SessionInit.decode(
            bytes(wire), my_box_priv, from_ed_pub,
        )
        self.assertIsNone(decoded,
                          "tampered wire should not decode")

    async def test_init_round_trip_with_python_ephemeral(self):
        """Python encode (random ephemeral) -> Python decode end-to-end."""
        for idx, v in enumerate(self.init_vectors):
            to_ed_pub = derive_ed_pub_from_seed(v["to_seed"])
            init = SessionInit(
                current=v["current"], next_pub=v["next"],
                key_seq=v["key_seq"], seq=v["seq"],
            )
            # No pinned keypair: full random path.
            wire = init.encode(
                v["from_seed"], to_ed_pub, type_byte=v["type_byte"],
            )
            my_box_priv = ed25519_priv_seed_to_curve25519(v["to_seed"])
            from_ed_pub = derive_ed_pub_from_seed(v["from_seed"])
            decoded = SessionInit.decode(wire, my_box_priv, from_ed_pub)
            self.assertIsNotNone(decoded,
                                 "round trip vector {0} failed".format(idx))
            self.assertEqual(decoded.current, v["current"])
            self.assertEqual(decoded.next, v["next"])
            self.assertEqual(decoded.key_seq, v["key_seq"])
            self.assertEqual(decoded.seq, v["seq"])

    async def test_traffic_wire_byte_parity(self):
        """SessionTypeTraffic wire bytes match Go's encoding."""
        for idx, v in enumerate(self.traffic_vectors):
            nonce_bytes = (b"\x00" * 16) + v["nonce"].to_bytes(8, "big")
            inner = v["next_pub"] + v["msg"]
            sealed = nacl_box.seal_precomputed(
                inner, nonce_bytes, v["shared"],
            )
            wire = (bytes([SESSION_TYPE_TRAFFIC])
                    + encode_uvarint(v["local_key_seq"])
                    + encode_uvarint(v["remote_key_seq"])
                    + encode_uvarint(v["nonce"])
                    + sealed)
            self.assertEqual(
                binascii.hexlify(wire).decode(),
                binascii.hexlify(v["wire"]).decode(),
                "TRAFFIC vector {0} byte mismatch".format(idx),
            )

    async def test_traffic_open_recovers_payload(self):
        """Opening the Go-produced traffic wire recovers next_pub + msg."""
        for idx, v in enumerate(self.traffic_vectors):
            nonce_bytes = (b"\x00" * 16) + v["nonce"].to_bytes(8, "big")
            # Skip header: type + 3 uvarints to find the sealed offset.
            from warpgate.overlay.yggdrasil.wire import decode_uvarint
            offset = 1
            _, consumed = decode_uvarint(v["wire"], offset)
            offset += consumed
            _, consumed = decode_uvarint(v["wire"], offset)
            offset += consumed
            _, consumed = decode_uvarint(v["wire"], offset)
            offset += consumed
            sealed = v["wire"][offset:]
            opened = nacl_box.open_precomputed(
                sealed, nonce_bytes, v["shared"],
            )
            self.assertIsNotNone(
                opened,
                "TRAFFIC vector {0} open failed".format(idx),
            )
            self.assertEqual(
                opened[:32], v["next_pub"],
                "vector {0} next_pub mismatch".format(idx),
            )
            self.assertEqual(
                opened[32:], v["msg"],
                "vector {0} msg mismatch".format(idx),
            )


if __name__ == "__main__":
    unittest.main()
