"""murmur3-128 sum256 byte-parity tests against bits-and-blooms reference."""
import binascii
import os
import unittest

from aionetiface.testing import AsyncTestCase

from warpgate.overlay.yggdrasil.murmur128 import sum128, sum256


VECTOR_PATH = os.path.join(
    os.path.dirname(__file__), "yggdrasil_murmur_vectors.txt"
)


def load_vectors():
    out = []
    with open(VECTOR_PATH, "r") as fh:
        for line in fh:
            parts = line.rstrip("\n").split("|")
            if len(parts) != 5:
                continue
            data_hex, h1, h2, h3, h4 = parts
            out.append((
                binascii.unhexlify(data_hex),
                int(h1, 16), int(h2, 16),
                int(h3, 16), int(h4, 16),
            ))
    return out


class TestMurmurSum256(AsyncTestCase):

    async def test_vectors_present(self):
        vectors = load_vectors()
        self.assertGreaterEqual(len(vectors), 15)

    async def test_sum256_matches_go(self):
        for data, h1, h2, h3, h4 in load_vectors():
            got = sum256(data)
            self.assertEqual(
                got, (h1, h2, h3, h4),
                "data={0}: got={1} expected={2}".format(
                    binascii.hexlify(data).decode(),
                    [hex(v) for v in got],
                    [hex(v) for v in (h1, h2, h3, h4)],
                ),
            )

    async def test_sum128_returns_first_two_of_sum256(self):
        for data, h1, h2, _h3, _h4 in load_vectors():
            self.assertEqual(sum128(data), (h1, h2))


# Large-input vectors generated by github.com/twmb/murmur3 (the same
# library bits-and-blooms uses underneath; both expose the canonical
# murmur3_128 hash so the outputs are byte-identical).  These exercise
# the multi-block bmix() path many times -- 4KB = 256 blocks, 64KB =
# 4096 blocks.  A bug in the block loop would only surface here, not
# in the existing small-input vectors.
#
# Each entry is (label, data_factory, h1, h2, h3, h4) where data_factory
# returns the test bytes -- we don't ship megabytes of hex in the test
# file, we synthesize the input procedurally and compare to known Go
# output.
def _zeros(n):
    return b"\x00" * n


def _ones(n):
    return b"\xaa" * n


def _seq(n):
    return bytes([i & 0xff for i in range(n)])


def _alternating(n):
    return bytes([0xa5 if (i & 1) == 0 else 0x5a for i in range(n)])


LARGE_MURMUR_VECTORS = (
    # (label, data, h1, h2, h3, h4)  -- h_n in hex
    # Sub-block boundary cases (existing file only has <=32-byte vectors).
    ("zeros16",
     _zeros(16),
     0x4bbd1bf27da918d6, 0xb465a9eccd791cb6,
     0xd8eef19160c1c32f, 0xa3f1ac6e80c5a57a),
    ("zeros32",
     _zeros(32),
     0x31723c284ade5cd0, 0x10c01d1bb3342d3c,
     0xb429f270a170c689, 0x99d2341d33a86831),
    ("zeros48",
     _zeros(48),
     0xd93e719d888c440d, 0x69e5584c1da70e4c,
     0x1d49cbc9228ab1ff, 0x88a68a761bf7d1fd),
    ("zeros96",
     _zeros(96),
     0x26497a6c2b02146c, 0xfeb7b1844fc42eba,
     0xfb523dc3f849a41f, 0x8f12014ff5fdd82c),
    # Multi-block cases -- 4KB+ to exercise the bmix() block loop.
    ("zeros4096",
     _zeros(4096),
     0x6ac4fe9480b3fb7a, 0xfb7003051ad6b21c,
     0xa85ccf8459af68a7, 0x1c0b3161020b4ea9),
    # Tail = 1 byte (4096 + 1)
    ("zeros4097",
     _zeros(4097),
     0x23c52d62066f196f, 0x6d7060a0264cee06,
     0x6f0d5993d1133fe6, 0x7f63ca193f5f361e),
    # Tail = 15 bytes (4096 + 15)
    ("zeros4111",
     _zeros(4111),
     0x772f51843cf860ee, 0x1444a8e4935f7d04,
     0x57c03238e68fb5e8, 0xed2062dc7aa058a7),
    # 8KB, exactly block-aligned
    ("zeros8192",
     _zeros(8192),
     0x148e41dfbb1c9176, 0x050eac45fa7a3dc6,
     0x3a03f3c7096683cd, 0x114c519aef0e45c9),
    # 64KB
    ("zeros65536",
     _zeros(65536),
     0xabc6794f59bc2b78, 0x4309e0a1ba50da30,
     0x56d029630e7eee24, 0x2f3e8e4dc6c7b1e9),
    # 4KB of 0xAA pattern
    ("aa4096",
     _ones(4096),
     0xc3580b536c9a1175, 0x28f200f9f56a858e,
     0xab8fef2a4d3140e6, 0x2b9edfe68cba5b1e),
    # 5000-byte sequential pattern (5000 = 312*16 + 8 -- partial tail)
    ("seq5000",
     _seq(5000),
     0x0d894cc4caf3c941, 0x6d898af5390d097a,
     0x3159d70717e0aec2, 0x012c0ac41feaf85d),
    # 100KB alternating 0xa5/0x5a pattern
    ("alt100000",
     _alternating(100000),
     0xf8eaf611113b2bf4, 0x56341e654ebe1a95,
     0x31f22c5051460912, 0x84fa230b7668bea6),
)


class TestMurmurLargeInputs(AsyncTestCase):
    """Multi-block + boundary inputs validated against Go's murmur3_128.

    The existing vector file tops out at 32 bytes -- it can't catch
    bugs in the block-loop machinery the bits-and-blooms bloom filter
    actually exercises (it hashes peer IDs that grow with the routing
    table).  These vectors fill the gap from 4KB up to 100KB.
    """

    async def test_sum256_large_matches_go(self):
        for label, data, h1, h2, h3, h4 in LARGE_MURMUR_VECTORS:
            got = sum256(data)
            self.assertEqual(
                got, (h1, h2, h3, h4),
                "{0} (len={1}): got={2} expected={3}".format(
                    label, len(data),
                    [hex(v) for v in got],
                    [hex(v) for v in (h1, h2, h3, h4)],
                ),
            )

    async def test_sum128_large_matches_first_two_of_sum256(self):
        for label, data, h1, h2, _h3, _h4 in LARGE_MURMUR_VECTORS:
            self.assertEqual(
                sum128(data), (h1, h2),
                "{0} (len={1}): sum128 mismatch".format(label, len(data)),
            )


class TestMurmurInternalConsistency(AsyncTestCase):
    """Self-consistency properties that should hold for any murmur3
    implementation -- catches regressions even without an external
    reference.
    """

    async def test_sum256_second_half_equals_sum128_of_data_plus_byte(self):
        """sum256(data)[2:4] == sum128(data + 0x01) -- the bits-and-blooms
        sum256 contract is exactly 'murmur128 || murmur128_of_data_with_0x01_appended'.
        """
        for n in (0, 1, 7, 8, 14, 15, 16, 17, 32, 33, 63, 64, 100, 4096, 4097):
            data = bytes([(i * 13) & 0xff for i in range(n)])
            h1, h2, h3, h4 = sum256(data)
            h3p, h4p = sum128(data + b"\x01")
            self.assertEqual(
                (h3, h4), (h3p, h4p),
                "n={0}: sum256 second-half disagrees with sum128(data + 0x01)".format(n),
            )

    async def test_sum128_is_deterministic(self):
        """Repeat calls must produce identical output."""
        data = b"hello world this is a determinism test"
        a = sum128(data)
        b = sum128(data)
        self.assertEqual(a, b)

    async def test_empty_input(self):
        """Empty input must not raise and must produce the documented value."""
        # The existing vector file pins the empty-input result; we
        # double-check via the unified interface to guard against
        # surface-level breakage (e.g. someone special-cases len==0
        # and accidentally short-circuits the finalize step).
        h1, h2, h3, h4 = sum256(b"")
        self.assertEqual(h1, 0x0000000000000000)
        self.assertEqual(h2, 0x0000000000000000)
        # The 0x01 appended virtually means h3/h4 != 0 even for empty
        # input.
        self.assertEqual(h3, 0x7ace5c908374fe16)
        self.assertEqual(h4, 0x778867e4430e6785)

    async def test_rejects_non_bytes_input(self):
        with self.assertRaises(ValueError):
            sum256("not bytes")
        with self.assertRaises(ValueError):
            sum256(12345)


if __name__ == "__main__":
    unittest.main()
