"""Byte-parity tests for warpgate.overlay.yggdrasil.address.

Test vectors generated by the real yggdrasil-go reference
implementation (``/tmp/gen_vectors/gen_vectors.go``) and stored in
``yggdrasil_address_vectors.txt`` -- one line per vector with three
hex fields:

    <pubkey_hex_64> <ipv6_addr_str> <subnet_hex_16>

If a single vector fails it means the Python port has drifted from
the Go reference -- regenerate the vectors against current upstream
to confirm before changing the port.
"""
import binascii
import os
import socket
import unittest
from aionetiface.testing import AsyncTestCase

from warpgate.overlay.yggdrasil.address import (
    PREFIX,
    PUBLIC_KEY_SIZE,
    ADDRESS_LEN,
    SUBNET_LEN,
    addr_for_key,
    subnet_for_key,
    get_key_from_address,
    get_key_from_subnet,
    address_is_valid,
    subnet_is_valid,
    ipv6_str_from_bytes,
    bytes_from_ipv6_str,
)


VECTOR_PATH = os.path.join(
    os.path.dirname(__file__), "yggdrasil_address_vectors.txt"
)


def load_vectors():
    """Return list of (pubkey_bytes, addr_str, subnet_bytes) tuples."""
    out = []
    with open(VECTOR_PATH, "r") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 3:
                continue
            pub_hex, addr_str, snet_hex = parts
            out.append((
                binascii.unhexlify(pub_hex),
                addr_str,
                binascii.unhexlify(snet_hex),
            ))
    return out


class TestYggdrasilAddressVectors(AsyncTestCase):
    """Byte-for-byte parity against the Go reference implementation."""

    async def test_vectors_present(self):
        """Sanity: the vectors file is non-empty."""
        vectors = load_vectors()
        self.assertTrue(len(vectors) >= 10,
                        "expected at least 10 vectors, got {0}".format(len(vectors)))

    async def test_addr_for_key_matches_go_reference(self):
        """addr_for_key() output matches yggdrasil-go's AddrForKey()."""
        for pub, addr_str_expected, _snet in load_vectors():
            addr = addr_for_key(pub)
            self.assertEqual(len(addr), ADDRESS_LEN)
            addr_str = ipv6_str_from_bytes(addr)
            self.assertEqual(
                addr_str, addr_str_expected,
                "pubkey {0}: got {1} expected {2}".format(
                    binascii.hexlify(pub).decode(),
                    addr_str, addr_str_expected,
                )
            )

    async def test_subnet_for_key_matches_go_reference(self):
        """subnet_for_key() output matches yggdrasil-go's SubnetForKey()."""
        for pub, _addr, snet_expected in load_vectors():
            snet = subnet_for_key(pub)
            self.assertEqual(len(snet), SUBNET_LEN)
            self.assertEqual(
                snet, snet_expected,
                "pubkey {0}: got {1} expected {2}".format(
                    binascii.hexlify(pub).decode(),
                    binascii.hexlify(snet).decode(),
                    binascii.hexlify(snet_expected).decode(),
                )
            )

    async def test_addr_starts_with_node_prefix(self):
        """Every derived address starts with 0x02 (node prefix)."""
        for pub, _addr, _snet in load_vectors():
            addr = addr_for_key(pub)
            self.assertEqual(addr[0], 0x02)
            self.assertTrue(address_is_valid(addr))

    async def test_subnet_starts_with_subnet_prefix(self):
        """Every derived subnet starts with 0x03 (subnet prefix)."""
        for pub, _addr, _snet in load_vectors():
            snet = subnet_for_key(pub)
            self.assertEqual(snet[0], 0x03)
            self.assertTrue(subnet_is_valid(snet))

    async def test_prefix_constant_matches_upstream(self):
        """PREFIX is exactly one byte 0x02 -- matches yggdrasil-go's GetPrefix()."""
        self.assertEqual(PREFIX, b"\x02")
        self.assertEqual(len(PREFIX), 1)

    async def test_addr_for_key_rejects_wrong_length(self):
        """Invalid pubkey lengths raise ValueError (upstream returns nil)."""
        with self.assertRaises(ValueError):
            addr_for_key(b"\x00" * 31)
        with self.assertRaises(ValueError):
            addr_for_key(b"\x00" * 33)
        with self.assertRaises(ValueError):
            addr_for_key(b"")

    async def test_subnet_for_key_rejects_wrong_length(self):
        """Invalid pubkey lengths raise ValueError."""
        with self.assertRaises(ValueError):
            subnet_for_key(b"\x00" * 31)

    async def test_get_key_recovers_leading_bits(self):
        """get_key_from_address recovers the leading bits of the pubkey.

        Match isn't byte-perfect -- the address only encodes ~112 bits
        of the 256-bit key -- but the leading bits up to the encoded
        portion must agree with the original key.
        """
        for pub, _addr, _snet in load_vectors():
            addr = addr_for_key(pub)
            recovered = get_key_from_address(addr)
            self.assertEqual(len(recovered), PUBLIC_KEY_SIZE)
            # The first ~14 bytes worth of info should match (depending
            # on the leading-ones count, the recoverable range varies).
            # Compare the address-roundtrip: recovered key, when
            # re-fed through addr_for_key, must yield the same address.
            re_addr = addr_for_key(recovered)
            self.assertEqual(re_addr, addr,
                "pubkey {0}: get_key roundtrip address mismatch".format(
                    binascii.hexlify(pub).decode()))

    async def test_get_key_from_subnet_matches_address_path(self):
        """Subnet → key recovery is consistent with address → key recovery."""
        for pub, _addr, _snet in load_vectors():
            snet = subnet_for_key(pub)
            addr = addr_for_key(pub)
            # Pad subnet to 16 bytes the same way get_key_from_subnet does.
            from_subnet = get_key_from_subnet(snet)
            from_addr_zeroed = get_key_from_address(
                snet + b"\x00" * (ADDRESS_LEN - SUBNET_LEN)
            )
            self.assertEqual(from_subnet, from_addr_zeroed)

    async def test_address_validity_checks(self):
        """address_is_valid / subnet_is_valid reject inputs of wrong length / prefix."""
        self.assertFalse(address_is_valid(b"\x02" + b"\x00" * 14))    # too short
        self.assertFalse(address_is_valid(b"\x00" * 16))              # wrong prefix
        self.assertTrue(address_is_valid(b"\x02" + b"\x00" * 15))     # OK
        self.assertFalse(subnet_is_valid(b"\x03" + b"\x00" * 6))      # too short
        self.assertFalse(subnet_is_valid(b"\x02" + b"\x00" * 7))      # wrong prefix
        self.assertTrue(subnet_is_valid(b"\x03" + b"\x00" * 7))       # OK

    async def test_ipv6_str_roundtrip(self):
        """ipv6_str_from_bytes and bytes_from_ipv6_str are inverses."""
        for pub, addr_str, _snet in load_vectors():
            addr = addr_for_key(pub)
            self.assertEqual(ipv6_str_from_bytes(addr), addr_str)
            self.assertEqual(bytes_from_ipv6_str(addr_str), addr)


if __name__ == "__main__":
    unittest.main()
