"""Byte-parity tests for the Yggdrasil version_metadata handshake codec.

Vectors generated by a Go program that calls into the upstream
``yggdrasil-go/src/core/version.go`` encode path (the field's
unexported, so the generator re-implements the same bytes inline;
its output is verified against the upstream encode path by the
yggdrasil-go test suite itself).

Each line in ``yggdrasil_handshake_vectors.txt``:

    seed_hex|password|priority|pubkey_hex|signature_hex|full_wire_hex
"""
import binascii
import os
import unittest

from aionetiface.testing import AsyncTestCase

from warpgate.overlay.yggdrasil.version import (
    VersionMetadata,
    HandshakeError,
    ERR_INVALID_PREAMBLE,
    ERR_INVALID_LENGTH,
    ERR_INCORRECT_PASSWORD,
    PROTOCOL_VERSION_MAJOR,
    PROTOCOL_VERSION_MINOR,
    PREAMBLE,
)
from warpgate.overlay.yggdrasil.blake2b import blake2b_hash


VECTOR_PATH = os.path.join(
    os.path.dirname(__file__),
    "yggdrasil_handshake_vectors.txt",
)


def load_vectors():
    """Return list of dicts, one per vector line."""
    out = []
    with open(VECTOR_PATH, "r") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            parts = line.split("|")
            if len(parts) != 6:
                continue
            seed_hex, password, priority, pub_hex, sig_hex, wire_hex = parts
            out.append({
                "seed": binascii.unhexlify(seed_hex),
                "password": password.encode("utf-8"),
                "priority": int(priority),
                "pub": binascii.unhexlify(pub_hex),
                "sig": binascii.unhexlify(sig_hex),
                "wire": binascii.unhexlify(wire_hex),
            })
    return out


class TestVersionMetadataEncode(AsyncTestCase):
    """Encoder output matches yggdrasil-go byte-for-byte."""

    async def test_encode_matches_go_reference(self):
        for v in load_vectors():
            meta = VersionMetadata(
                major_ver=PROTOCOL_VERSION_MAJOR,
                minor_ver=PROTOCOL_VERSION_MINOR,
                public_key=v["pub"],
                priority=v["priority"],
            )
            got = meta.encode(v["seed"], password=v["password"])
            self.assertEqual(
                got, v["wire"],
                "wire mismatch: pw={0} prio={1}\n got: {2}\nwant: {3}".format(
                    v["password"], v["priority"],
                    got.hex(), v["wire"].hex(),
                )
            )

    async def test_preamble_constant(self):
        self.assertEqual(PREAMBLE, b"meta")

    async def test_encode_rejects_bad_seed_length(self):
        meta = VersionMetadata(public_key=b"\x00" * 32)
        with self.assertRaises(ValueError):
            meta.encode(b"\x00" * 31)
        with self.assertRaises(ValueError):
            meta.encode(b"")

    async def test_encode_rejects_bad_pubkey_length(self):
        meta = VersionMetadata(public_key=b"\x00" * 31)
        with self.assertRaises(ValueError):
            meta.encode(b"\x00" * 32)


class TestVersionMetadataDecode(AsyncTestCase):
    """Decoder accepts upstream-encoded bytes and recovers all fields."""

    async def test_decode_roundtrips_all_vectors(self):
        for v in load_vectors():
            meta = VersionMetadata.decode(v["wire"], password=v["password"])
            self.assertEqual(meta.major_ver, PROTOCOL_VERSION_MAJOR)
            self.assertEqual(meta.minor_ver, PROTOCOL_VERSION_MINOR)
            self.assertEqual(meta.public_key, v["pub"])
            self.assertEqual(meta.priority, v["priority"])

    async def test_decode_rejects_bad_preamble(self):
        v = load_vectors()[0]
        bad = b"X" + v["wire"][1:]
        with self.assertRaises(HandshakeError) as ctx:
            VersionMetadata.decode(bad, password=v["password"])
        self.assertEqual(str(ctx.exception), ERR_INVALID_PREAMBLE)

    async def test_decode_rejects_truncated_header(self):
        with self.assertRaises(HandshakeError) as ctx:
            VersionMetadata.decode(b"met", password=b"")
        self.assertEqual(str(ctx.exception), ERR_INVALID_LENGTH)

    async def test_decode_rejects_wrong_password(self):
        v = load_vectors()[3]  # The one with a non-empty password.
        with self.assertRaises(HandshakeError) as ctx:
            VersionMetadata.decode(v["wire"], password=b"wrongpassword")
        self.assertEqual(str(ctx.exception), ERR_INCORRECT_PASSWORD)

    async def test_decode_tlv_unknown_op_is_ignored(self):
        """Forward-compat: an unknown TLV must NOT raise."""
        v = load_vectors()[0]
        wire = bytearray(v["wire"])
        # Inject an unknown TLV (op=999, oplen=4, value=\x00\x00\x00\x00)
        # at the END of the TLV body, before the signature.
        sig_start = len(wire) - 64
        extra_tlv = b"\x03\xe7\x00\x04\x00\x00\x00\x00"  # op=999, len=4
        new_wire = bytes(wire[:sig_start]) + extra_tlv + bytes(wire[sig_start:])
        # Re-pack the length field.
        body_len = len(new_wire) - 6
        new_wire = bytes(new_wire[:4]) + body_len.to_bytes(2, "big") + bytes(new_wire[6:])
        # Decoder accepts; the unknown TLV is silently skipped.
        meta = VersionMetadata.decode(new_wire, password=v["password"])
        # Pubkey/priority survive intact.
        self.assertEqual(meta.public_key, v["pub"])
        self.assertEqual(meta.priority, v["priority"])


class TestVersionMetadataCheck(AsyncTestCase):
    """check() enforces matching protocol version + valid pubkey."""

    async def test_check_passes_for_valid(self):
        meta = VersionMetadata(public_key=b"\x00" * 32)
        self.assertTrue(meta.check())

    async def test_check_rejects_wrong_major(self):
        meta = VersionMetadata(major_ver=99, public_key=b"\x00" * 32)
        self.assertFalse(meta.check())

    async def test_check_rejects_wrong_minor(self):
        meta = VersionMetadata(minor_ver=99, public_key=b"\x00" * 32)
        self.assertFalse(meta.check())

    async def test_check_rejects_bad_pubkey_size(self):
        meta = VersionMetadata(public_key=b"\x00" * 31)
        self.assertFalse(meta.check())


class TestBlake2bIntegration(AsyncTestCase):
    """Blake2b output for the password-key + pubkey-message case used by handshake."""

    async def test_blake2b_keyed_matches_go_implicit(self):
        """If our blake2b were wrong, encode() would produce a different signature
        than Go and the byte-parity test above would catch it.  This test
        just asserts the keyed mode runs, the output length is right, and
        it changes when the password changes (sanity for the integration)."""
        pub = b"\x00" * 32
        d1 = blake2b_hash(pub, key=b"", digest_size=64)
        d2 = blake2b_hash(pub, key=b"secret", digest_size=64)
        d3 = blake2b_hash(pub, key=b"different", digest_size=64)
        self.assertEqual(len(d1), 64)
        self.assertNotEqual(d1, d2)
        self.assertNotEqual(d2, d3)


if __name__ == "__main__":
    unittest.main()
