"""Yggdrasil address + subnet derivation -- byte-compatible with yggdrasil-go.

Port of ``src/address/address.go`` from
https://github.com/yggdrasil-network/yggdrasil-go.

The algorithm (paraphrased from upstream docs + source):

  An IPv6 address derived from an ed25519 public key is 128 bits laid
  out as ``[prefix][ones][packed_bits...]`` where:

    * ``prefix``    = single byte ``0x02`` (the ``GetPrefix()`` value).
    * ``ones``      = number of leading ``1`` bits in the BITWISE INVERSE
                      of the public key.  Encoded as a single byte.
    * ``packed_bits`` = the inverse-of-key bit stream after stripping
                      the leading ``ones`` ``1``s AND the first ``0``
                      that terminates them, packed MSB-first into bytes
                      until the address is full (128 bits total).

  The ``0x02`` prefix marks the address as "node address"; the
  matching subnet form sets the low bit so the prefix is ``0x03``
  ("/64 prefix").  This is why Yggdrasil addresses live in
  ``200::/8`` while subnets live in ``300::/8`` -- together they
  cover the ``200::/7`` family.

  Reverse derivation (``Address.get_key``) is partial: only the bits
  the address can hold are recoverable, so the returned key has
  trailing zero bits where the original key's lower bits used to be.

The implementation uses pure stdlib bit math (no ed25519 dependency
in this module) so address derivation runs on the Python 3.5 floor
without any optional crypto packages.

Wire-compat test vectors live in
``tests/yggdrasil_address_vectors.txt`` and are generated by the
upstream Go reference impl; see ``test_yggdrasil_address.py``.
"""
from aionetiface import fstr


# Single-byte prefix that opens every Yggdrasil node address.
# Subnet form is this byte ORed with 0x01 (= 0x03).
PREFIX = b"\x02"

# ed25519 public key size; matches upstream's ed25519.PublicKeySize.
PUBLIC_KEY_SIZE = 32

# Address / subnet byte sizes (the Go types are fixed-size arrays).
ADDRESS_LEN = 16
SUBNET_LEN = 8


def get_prefix():
    """Return the one-byte Yggdrasil node-address prefix (``b'\\x02'``).

    Helper kept for one-to-one parity with upstream's ``GetPrefix()``;
    callers that just need the byte can use ``PREFIX`` directly.
    """
    return PREFIX


def address_is_valid(addr_bytes):
    """Return True if ``addr_bytes`` (16 bytes) starts with the node prefix.

    Mirrors upstream ``(*Address).IsValid()`` -- the prefix is a single
    byte that must match exactly, no consideration of the next bit.
    """
    if not isinstance(addr_bytes, (bytes, bytearray)):
        raise ValueError("addr_bytes must be bytes")
    if len(addr_bytes) != ADDRESS_LEN:
        return False
    for idx in range(len(PREFIX)):
        if addr_bytes[idx] != PREFIX[idx]:
            return False
    return True


def subnet_is_valid(snet_bytes):
    """Return True if ``snet_bytes`` (8 bytes) starts with the subnet prefix.

    Subnet form mirrors the address prefix on every byte except the
    last byte of the prefix, where the low bit must be 1 (= ``0x03``).
    """
    if not isinstance(snet_bytes, (bytes, bytearray)):
        raise ValueError("snet_bytes must be bytes")
    if len(snet_bytes) != SUBNET_LEN:
        return False
    last = len(PREFIX) - 1
    for idx in range(last):
        if snet_bytes[idx] != PREFIX[idx]:
            return False
    return snet_bytes[last] == (PREFIX[last] | 0x01)


def addr_for_key(public_key):
    """Return the 16-byte IPv6 address derived from an ed25519 public key.

    ``public_key`` is the 32-byte ed25519 public key (raw bytes).
    Raises ``ValueError`` if the length is wrong (upstream returns
    ``nil``; we raise for explicitness at the API boundary).
    """
    if not isinstance(public_key, (bytes, bytearray)):
        raise ValueError("public_key must be bytes")
    if len(public_key) != PUBLIC_KEY_SIZE:
        raise ValueError(fstr(
            "public_key length {0}, expected {1}",
            (len(public_key), PUBLIC_KEY_SIZE),
        ))

    # Bitwise inverse of every byte of the key.  Upstream uses a
    # mutable buffer; we build a fresh bytes object since Python
    # bytes are immutable anyway.
    inverted = bytes((b ^ 0xFF) for b in public_key)

    # Walk the bit stream MSB-first.  Count the leading 1s ("ones"),
    # then SKIP the first 0 that ends the run, then start packing the
    # remaining bits MSB-first into output bytes.
    ones = 0
    done = False
    packed = bytearray()
    bits = 0
    n_bits = 0
    total_bits = 8 * len(inverted)
    for idx in range(total_bits):
        # Bit value at position ``idx`` reading the byte MSB-first --
        # upstream's formula: ``(buf[idx/8] & (0x80 >> idx%8)) >> 7-idx%8``.
        byte_index = idx // 8
        bit_index = idx % 8
        bit = (inverted[byte_index] >> (7 - bit_index)) & 1
        if not done and bit != 0:
            ones += 1
            continue
        if not done and bit == 0:
            done = True
            continue
        bits = (bits << 1) | bit
        n_bits += 1
        if n_bits == 8:
            packed.append(bits)
            bits = 0
            n_bits = 0

    # Layout the address: [prefix][ones][packed...], padded with
    # implicit zeros if packed runs short, truncated to 16 bytes.
    out = bytearray(ADDRESS_LEN)
    out[: len(PREFIX)] = PREFIX
    out[len(PREFIX)] = ones & 0xFF
    body_len = ADDRESS_LEN - len(PREFIX) - 1
    body = bytes(packed[:body_len])
    out[len(PREFIX) + 1 : len(PREFIX) + 1 + len(body)] = body
    return bytes(out)


def subnet_for_key(public_key):
    """Return the 8-byte /64 subnet derived from an ed25519 public key.

    Computed by taking the first 8 bytes of ``addr_for_key`` and
    ORing the last byte of the prefix with ``0x01`` (so ``0x02`` →
    ``0x03``).  Matches upstream ``SubnetForKey``.
    """
    addr = addr_for_key(public_key)
    out = bytearray(addr[:SUBNET_LEN])
    last = len(PREFIX) - 1
    out[last] = out[last] | 0x01
    return bytes(out)


def get_key_from_address(addr_bytes):
    """Recover the leading bits of the ed25519 public key from an address.

    The address only carries ~112 bits of the original 256-bit key,
    so the returned bytes contain those bits plus trailing zeros.
    Upstream callers use this for DHT lookups, not for full key
    recovery.  Mirrors ``(*Address).GetKey()``.
    """
    if not isinstance(addr_bytes, (bytes, bytearray)):
        raise ValueError("addr_bytes must be bytes")
    if len(addr_bytes) != ADDRESS_LEN:
        raise ValueError(fstr(
            "addr_bytes length {0}, expected {1}",
            (len(addr_bytes), ADDRESS_LEN),
        ))

    key = bytearray(PUBLIC_KEY_SIZE)
    ones = addr_bytes[len(PREFIX)]

    # Stamp ``ones`` leading 1 bits into the (still inverted) key
    # buffer.  Index ``ones`` itself stays 0 -- that's the delimiting
    # ``0`` bit that gets skipped on the forward pass.
    for idx in range(ones):
        key[idx // 8] |= 0x80 >> (idx % 8)

    # Now copy bits from the address body into the key starting at
    # bit position ``ones + 1``.  ``addr_offset`` is the first bit
    # position of the address body (= 8*prefix_len + 8 for the ones
    # byte itself).  Note: upstream rebinds ``idx`` mid-loop -- we
    # use separate names for clarity.
    key_offset = ones + 1
    addr_offset = 8 * len(PREFIX) + 8
    addr_bits = 8 * len(addr_bytes)
    for addr_bit_idx in range(addr_offset, addr_bits):
        byte = addr_bytes[addr_bit_idx // 8]
        bit_val = byte & (0x80 >> (addr_bit_idx % 8))
        # Shift the captured bit into the LSB position before re-
        # shifting it into its destination slot in the key byte --
        # mirrors the two-step shift dance upstream does.
        bit_val = (bit_val << (addr_bit_idx % 8)) & 0xFF
        key_bit_idx = key_offset + (addr_bit_idx - addr_offset)
        bit_val = bit_val >> (key_bit_idx % 8)
        key_byte = key_bit_idx // 8
        if key_byte >= len(key):
            break
        key[key_byte] |= bit_val & 0xFF

    # Final pass: invert every byte back, mirroring the forward pass.
    for i in range(len(key)):
        key[i] = key[i] ^ 0xFF
    return bytes(key)


def get_key_from_subnet(snet_bytes):
    """Recover partial pubkey from a subnet prefix.

    Internally pads to 16 bytes (zero fill) and reuses
    ``get_key_from_address``.  Matches upstream
    ``(*Subnet).GetKey()``.
    """
    if not isinstance(snet_bytes, (bytes, bytearray)):
        raise ValueError("snet_bytes must be bytes")
    if len(snet_bytes) != SUBNET_LEN:
        raise ValueError(fstr(
            "snet_bytes length {0}, expected {1}",
            (len(snet_bytes), SUBNET_LEN),
        ))
    padded = bytes(snet_bytes) + b"\x00" * (ADDRESS_LEN - SUBNET_LEN)
    return get_key_from_address(padded)


def ipv6_str_from_bytes(addr_bytes):
    """Return the canonical IPv6 string form of a 16-byte address.

    Wraps stdlib ``socket.inet_ntop`` because the wire format and
    the test-vector format use canonical-IPv6 strings on the
    address side (the ``200::`` form).
    """
    import socket
    if not isinstance(addr_bytes, (bytes, bytearray)):
        raise ValueError("addr_bytes must be bytes")
    if len(addr_bytes) != ADDRESS_LEN:
        raise ValueError(fstr(
            "addr_bytes length {0}, expected {1}",
            (len(addr_bytes), ADDRESS_LEN),
        ))
    return socket.inet_ntop(socket.AF_INET6, bytes(addr_bytes))


def bytes_from_ipv6_str(addr_str):
    """Return the 16-byte address from a canonical IPv6 string."""
    import socket
    return socket.inet_pton(socket.AF_INET6, str(addr_str))
